// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDocuMgm.Infrastructure.Data;

#nullable disable

namespace MyDocuMgm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MyDocuMgmDbContext))]
    partial class MyDocuMgmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDocuMgm.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "PLACE",
                            DisplayName = "가볼곳",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "COOKING",
                            DisplayName = "요리",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "EXERCISE",
                            DisplayName = "운동",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "CLEANING_LAUNDRY",
                            DisplayName = "청소&세탁",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "TRAVEL",
                            DisplayName = "여행",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "PHOTO",
                            DisplayName = "사진",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "STUDY",
                            DisplayName = "공부",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "PRODUCT",
                            DisplayName = "제품",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "PHONE_COMPUTER",
                            DisplayName = "폰&컴",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Code = "TIP",
                            DisplayName = "팁",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Code = "OTHER",
                            DisplayName = "기타",
                            IsActive = true,
                            RowVersion = new byte[0],
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CategorySearchAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "AttributeKey")
                        .IsUnique();

                    b.HasIndex("CategoryId", "IsActive", "IsSearchable", "SortOrder");

                    b.ToTable("CategorySearchAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0002-000000000001"),
                            AttributeKey = "primaryIngredient",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayName = "주재료",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0002-000000000002"),
                            AttributeKey = "difficulty",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayName = "난이도",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0002-000000000003"),
                            AttributeKey = "time",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayName = "소요시간",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0008-000000000001"),
                            AttributeKey = "brand",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            DisplayName = "브랜드",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0008-000000000002"),
                            AttributeKey = "store",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            DisplayName = "구매처",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0008-000000000003"),
                            AttributeKey = "price",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            DisplayName = "가격대",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0001-000000000001"),
                            AttributeKey = "region",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayName = "지역",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0001-000000000002"),
                            AttributeKey = "parking",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayName = "주차",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0005-000000000001"),
                            AttributeKey = "destination",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayName = "국가·지역",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0005-000000000002"),
                            AttributeKey = "transport",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayName = "교통",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0003-000000000001"),
                            AttributeKey = "targetArea",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayName = "운동 부위",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0003-000000000002"),
                            AttributeKey = "equipment",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayName = "준비물",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0004-000000000001"),
                            AttributeKey = "target",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayName = "대상",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0004-000000000002"),
                            AttributeKey = "supplies",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayName = "세제·제품",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0006-000000000001"),
                            AttributeKey = "camera",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            DisplayName = "기기",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0006-000000000002"),
                            AttributeKey = "location",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            DisplayName = "촬영 장소",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0007-000000000001"),
                            AttributeKey = "subject",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            DisplayName = "분야",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0007-000000000002"),
                            AttributeKey = "resource",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            DisplayName = "참고 자료",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0009-000000000001"),
                            AttributeKey = "deviceOrOs",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            DisplayName = "기기·OS",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0009-000000000002"),
                            AttributeKey = "problem",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            DisplayName = "문제 유형",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0010-000000000001"),
                            AttributeKey = "situation",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000010"),
                            DisplayName = "적용 상황",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0010-000000000002"),
                            AttributeKey = "keyPoint",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000010"),
                            DisplayName = "주제",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0011-000000000001"),
                            AttributeKey = "customLabel",
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000011"),
                            DisplayName = "주제",
                            IsActive = true,
                            IsSearchable = true,
                            RowVersion = new byte[0],
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CleaningLaundryDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Precautions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Supplies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Target")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("CleaningLaundryDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentWorkflowStep")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("URL");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailContent")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("CurrentWorkflowStep", "UpdatedAtUtc");

                    b.HasIndex("IsDeleted", "UpdatedAtUtc");

                    b.HasIndex("CategoryId", "Status", "IsFavorite");

                    b.ToTable("Contents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contents_CurrentWorkflowStep", "[CurrentWorkflowStep] IN ('URL','ANALYSIS_REVIEW','CATEGORY_EDIT','MEDIA','DETAIL','BLOG_DRAFT','COMPLETED')");

                            t.HasCheckConstraint("CK_Contents_ExperienceStatus", "[ExperienceStatus] IN ('NONE','WANT_TO_TRY','TRIED')");

                            t.HasCheckConstraint("CK_Contents_Status", "[Status] IN ('INBOX','REVIEW_REQUIRED','READY','DRAFTED','PUBLISHED','ARCHIVED')");

                            t.HasCheckConstraint("CK_Contents_Visibility", "[Visibility] IN ('PRIVATE','PUBLIC_ALLOWED')");
                        });
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ContentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("ContentId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ContentSteps", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ContentTag", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentTags", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CookingDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CookingMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PreparationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.ToTable("CookingDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CookingIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IngredientType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("부재료");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentId", "SortOrder")
                        .IsUnique();

                    b.ToTable("CookingIngredients", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ExerciseDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetArea")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("ExerciseDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublicAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long?>("SourceTimestampMs")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath")
                        .IsUnique();

                    b.HasIndex("Sha256");

                    b.HasIndex("ContentId", "Sha256");

                    b.HasIndex("ContentId", "SortOrder");

                    b.HasIndex("ContentId", "IsSelected", "SourceTimestampMs");

                    b.ToTable("MediaAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaAssets_StorageStatus", "[StorageStatus] IN ('PENDING','READY','FAILED')");
                        });
                });

            modelBuilder.Entity("MyDocuMgm.Domain.OtherDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CustomLabel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("OtherDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PhoneComputerDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppOrProgram")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceOrOs")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Problem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Solution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("ContentId");

                    b.ToTable("PhoneComputerDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PhotoDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Camera")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Lens")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShootingSettings")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("PhotoDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PlaceDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BusinessHours")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParkingInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecommendedMenuOrSpot")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("PlaceDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ProductDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PurchasePlace")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("ProductDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.SourceEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SourceTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("SourceEvidence", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.StudyDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LearningGoal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Resource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewCycle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("StudyDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.TipDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyPoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Precautions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Situation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("TipDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.TravelDetails", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BestSeason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BudgetNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Destination")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Transportation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentId");

                    b.ToTable("TravelDetails", (string)null);
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CategorySearchAttribute", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Category", "Category")
                        .WithMany("SearchAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CleaningLaundryDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("CleaningLaundryDetails")
                        .HasForeignKey("MyDocuMgm.Domain.CleaningLaundryDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Content", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ContentStep", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithMany("Steps")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDocuMgm.Domain.MediaAsset", "MediaAsset")
                        .WithMany("ContentSteps")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ContentTag", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithMany("ContentTags")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDocuMgm.Domain.Tag", "Tag")
                        .WithMany("ContentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CookingDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("CookingDetails")
                        .HasForeignKey("MyDocuMgm.Domain.CookingDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CookingIngredient", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.CookingDetails", "CookingDetails")
                        .WithMany("Ingredients")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookingDetails");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ExerciseDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("ExerciseDetails")
                        .HasForeignKey("MyDocuMgm.Domain.ExerciseDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.MediaAsset", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithMany("MediaAssets")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.OtherDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("OtherDetails")
                        .HasForeignKey("MyDocuMgm.Domain.OtherDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PhoneComputerDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("PhoneComputerDetails")
                        .HasForeignKey("MyDocuMgm.Domain.PhoneComputerDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PhotoDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("PhotoDetails")
                        .HasForeignKey("MyDocuMgm.Domain.PhotoDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.PlaceDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("PlaceDetails")
                        .HasForeignKey("MyDocuMgm.Domain.PlaceDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.ProductDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("ProductDetails")
                        .HasForeignKey("MyDocuMgm.Domain.ProductDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.SourceEvidence", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithMany("SourceEvidence")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.StudyDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("StudyDetails")
                        .HasForeignKey("MyDocuMgm.Domain.StudyDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.TipDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("TipDetails")
                        .HasForeignKey("MyDocuMgm.Domain.TipDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.TravelDetails", b =>
                {
                    b.HasOne("MyDocuMgm.Domain.Content", "Content")
                        .WithOne("TravelDetails")
                        .HasForeignKey("MyDocuMgm.Domain.TravelDetails", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Category", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("SearchAttributes");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Content", b =>
                {
                    b.Navigation("CleaningLaundryDetails");

                    b.Navigation("ContentTags");

                    b.Navigation("CookingDetails");

                    b.Navigation("ExerciseDetails");

                    b.Navigation("MediaAssets");

                    b.Navigation("OtherDetails");

                    b.Navigation("PhoneComputerDetails");

                    b.Navigation("PhotoDetails");

                    b.Navigation("PlaceDetails");

                    b.Navigation("ProductDetails");

                    b.Navigation("SourceEvidence");

                    b.Navigation("Steps");

                    b.Navigation("StudyDetails");

                    b.Navigation("TipDetails");

                    b.Navigation("TravelDetails");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.CookingDetails", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.MediaAsset", b =>
                {
                    b.Navigation("ContentSteps");
                });

            modelBuilder.Entity("MyDocuMgm.Domain.Tag", b =>
                {
                    b.Navigation("ContentTags");
                });
#pragma warning restore 612, 618
        }
    }
}
